name: Automacao Mensal de Contas

on:
  schedule:
    # Executa todo dia 1 de cada mês às 09:00 AM UTC (aprox. 06:00 AM no Brasil)
    - cron: '0 9 1 * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  processar_relatorio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias de sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils libzbar0

    - name: Instalar bibliotecas Python
      run: |
        python -m pip install --upgrade pip
        pip install -r RelatorioContasMes/requirements.txt

    - name: Executar script de automacao
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
        CALLMEBOT_APIKEY: ${{ secrets.CALLMEBOT_APIKEY }}
      run: |
        cd RelatorioContasMes
        python script.py
